# Archivo: .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Se ejecuta solo cuando haces push a la rama principal (main)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build 
        run: |
          npm install # Instala las dependencias
          npm run build # Ejecuta el comando de compilaciÃ³n de Vite (crea la carpeta dist)
          
      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Es importante que el token se configure con permisos de 'write'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Ruta de la carpeta de salida (output) que creÃ³ npm run build
          publish_dir: ./dist 
          # Fuerza el push a una rama separada (gh-pages)
          publish_branch: gh-pages